spring:
  datasource:
    url: jdbc:mysql://192.168.1.164:3306/machat?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

server:
  port: 8080
