spring:
  datasource:
    url: jdbc:mysql://localhost:3306/machat?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 25000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 500000
      pool-name: DatebookHikariCP
      max-lifetime: 28740000
      connection-test-query: SELECT 1
server:
  port: 8081


mybatis:
  type-aliases-package: com.ma.bean
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.ma.util.MyMapper
  not-empty: false
  identity: MYSQL

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 80
    height: 80
  tracker-list:
    - 192.168.25.133:22122